[buildPlans.DigitalGecko]
family = "Digital Gecko"
spacing = "normal"
serifs = "sans"
noCvSs = false
exportGlyphNames = false

  [buildPlans.DigitalGecko.variants]
  inherits = "ss12"

    [buildPlans.DigitalGecko.variants.design]
    one = "no-base"
    five = "oblique-flat-serifless"
    seven = "bend-serifed"
    zero = "oval-tall-slashed"
    capital-a = "straight-top-serifed"
    capital-b = "standard-unilateral-serifed"
    capital-c = "unilateral-inward-serifed"
    capital-d = "more-rounded-unilateral-serifed"
    capital-e = "top-left-serifed"
    capital-f = "top-left-serifed"
    capital-g = "toothless-corner-inward-serifed-hooked"
    capital-h = "top-left-serifed"
    capital-j = "serifed-both-sides"
    capital-k = "straight-top-left-serifed"
    capital-l = "motion-serifed"
    capital-m = "hanging-motion-serifed"
    capital-n = "standard-motion-serifed"
    capital-p = "closed-motion-serifed"
    capital-q = "detached-bend-tailed"
    capital-r = "straight-top-left-serifed"
    capital-s = "unilateral-inward-serifed"
    capital-u = "toothless-rounded-unilateral-motion-serifed"
    capital-v = "straight-motion-serifed"
    capital-w = "straight-motion-serifed"
    capital-x = "straight-unilateral-motion-serifed"
    capital-y = "straight-motion-serifed"
    capital-z = "straight-top-serifed-with-crossbar"
    b = "toothless-corner-serifed"
    d = "toothless-corner-serifed"
    h = "straight-top-left-serifed"
    k = "symmetric-touching-top-left-serifed"
    q = "earless-corner-tailed-serifless"
    u = "toothless-corner-serifless"
    v = "straight-motion-serifed"
    w = "straight-motion-serifed"
    x = "straight-unilateral-motion-serifed"
    y = "straight-turn-motion-serifed"
    z = "straight-serifless-with-crossbar"
    long-s = "bent-hook-tailed"
    capital-thorn = "motion-serifed"
    lower-thorn = "motion-serifed"
    lower-alpha = "barred-earless-rounded"
    capital-gamma = "top-right-serifed"
    lower-theta = "cursive"
    lower-lambda = "tailed-turn"
    lower-nu = "straight-serifed"
    lower-phi = "cursive"
    lower-chi = "straight-unilateral-motion-serifed"
    lower-psi = "flat-top-serifed"
    partial-derivative = "curly-bar"
    cyrl-a = "double-storey-toothless-corner"
    cyrl-ve = "standard-serifless"
    cyrl-capital-ze = "unilateral-inward-serifed"
    cyrl-capital-ka = "symmetric-touching-top-left-serifed"
    cyrl-capital-en = "top-left-serifed"
    cyrl-capital-er = "closed-motion-serifed"
    cyrl-er = "earless-corner-serifless"
    cyrl-capital-u = "straight-turn-motion-serifed"
    cyrl-u = "straight-turn-motion-serifed"
    cyrl-ef = "top-serifed"
    cyrl-che = "tailed"
    cyrl-yeri = "round"
    cyrl-yery = "round-tailed"
    cyrl-capital-e = "unilateral-inward-serifed"
    cyrl-capital-ya = "straight-motion-serifed"
    tilde = "low"
    asterisk = "penta-low"
    underscore = "above-baseline"
    brace = "curly"
    at = "fourfold"
    dollar = "slanted-through"
    cent = "slanted-through"
    bar = "force-upright"
    pilcrow = "high"
    lig-equal-chain = "without-notch"

  [buildPlans.DigitalGecko.ligations]
  inherits = "dlig"

[buildPlans.DigitalGecko.slopes.Upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"

[buildPlans.DigitalGecko.slopes.Italic]
angle = 9.4
shape = "italic"
menu = "italic"
css = "italic"

# TTC collection (for super-ttc build)
[collectPlans.DigitalGecko]
from = ["DigitalGecko"]
