[buildPlans.DigitalGecko]
family = "Digital Gecko"
spacing = "normal"
serifs = "sans"
noCvSs = false
exportGlyphNames = false

  [buildPlans.DigitalGecko.variants]
  inherits = "ss09"

    [buildPlans.DigitalGecko.variants.design]
    one = "no-base"
    three = "flat-top-serifless"
    four = "semi-open-serifless"
    five = "oblique-flat-serifless"
    six = "straight-bar"
    seven = "curly-serifed"
    eight = "crossing-asymmetric"
    nine = "straight-bar"
    zero = "slashed"
    capital-a = "straight-top-serifed"
    capital-b = "standard-unilateral-serifed"
    capital-c = "unilateral-serifed"
    capital-d = "more-rounded-bilateral-serifed"
    capital-e = "top-left-serifed"
    capital-f = "top-left-serifed"
    capital-g = "toothless-corner-serifless-capped"
    capital-h = "top-left-serifed"
    capital-j = "serifed-both-sides"
    capital-k = "straight-top-left-serifed"
    capital-l = "motion-serifed"
    capital-m = "hanging-motion-serifed"
    capital-n = "standard-motion-serifed"
    capital-p = "closed-motion-serifed"
    capital-q = "detached-bend-tailed"
    capital-r = "straight-top-left-serifed"
    capital-v = "straight-motion-serifed"
    capital-w = "straight-motion-serifed"
    capital-x = "straight-unilateral-motion-serifed"
    capital-y = "straight-motion-serifed"
    capital-z = "straight-top-serifed-with-crossbar"
    a = "double-storey-toothless-corner"
    b = "toothless-corner-serifless"
    d = "toothless-corner-serifless"
    g = "single-storey-earless-corner"
    i = "serifed-flat-tailed"
    k = "straight-serifless"
    m = "earless-corner-double-arch-bottom-right-serifed"
    n = "earless-corner-straight-motion-serifed"
    p = "earless-corner-serifless"
    q = "earless-corner-tailed-serifless"
    r = "earless-corner-serifless"
    u = "toothless-corner-serifless"
    v = "straight-motion-serifed"
    w = "straight-serifless"
    z = "straight-serifless-with-crossbar"
    long-s = "bent-hook-diagonal-tailed"
    lower-eth = "curly-bar"
    cyrl-a = "double-storey-toothless-corner"
    cyrl-ve = "standard-interrupted-serifless"
    cyrl-zhe = "cursive"
    cyrl-capital-ze = "unilateral-serifed"
    cyrl-capital-ka = "straight-top-left-serifed"
    cyrl-ka = "straight-serifless"
    cyrl-capital-en = "top-left-serifed"
    cyrl-capital-er = "closed-motion-serifed"
    cyrl-er = "earless-corner-serifless"
    cyrl-capital-u = "straight-turn-motion-serifed"
    cyrl-capital-ya = "straight-motion-serifed"
    caret = "high"
    brace = "curly-flat-boundary"
    at = "compact"
    dollar = "through"
    percent = "rings-continuous-slash"
    micro-sign = "toothless-corner-serifless"
    lig-equal-chain = "without-notch"

  [buildPlans.DigitalGecko.ligations]
  inherits = "dlig"

# TTC collection (for super-ttc build)
[collectPlans.DigitalGecko]
from = ["DigitalGecko"]
